////////////////////////////////////////////////////////////////////
//DeRap: animals\gallus_gallus_domesticus_feminam\config.bin
//Produced from mikero's Dos Tools Dll version 7.16
//https://armaservices.maverick-applications.com/Products/MikerosDosTools/default
//'now' is Sun Jul 28 07:46:05 2019 : 'file' last modified on Mon Dec 19 09:52:40 2016
////////////////////////////////////////////////////////////////////

#define _ARMA_

//(12 Enums)
enum {
	destructengine = 2,
	destructdefault = 6,
	destructwreck = 7,
	destructtree = 3,
	destructtent = 4,
	stabilizedinaxisx = 1,
	stabilizedinaxisy = 2,
	destructno = 0,
	stabilizedinaxesboth = 3,
	stabilizedinaxesnone = 0,
	destructman = 5,
	destructbuilding = 1
};

class CfgPatches
{
	class DZ_Animals_gallus_gallus_domesticus_feminam
	{
		units[] = {"Animal_GallusGallusDomesticusF_Brown","Animal_GallusGallusDomesticusF_Spotted","Animal_GallusGallusDomesticusF_White"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Animals"};
	};
};
class CfgVehicles
{
	class AnimalBase;
	class Animal_GallusGallusDomesticusF: AnimalBase
	{
		class SoundEnvironExt
		{
			normal[] = {{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_2",1,1,50}}};
			normalExt[] = {{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_2",1,1,50}}};
			concrete_int[] = {{"\dz\sounds\effects\animals\movement\bird_\concrete\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\concrete\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\concrete\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\concrete\bodyfall_2",1,1,50}}};
			concrete_ext[] = {{"\dz\sounds\effects\animals\movement\bird_\concrete\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\concrete\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\concrete\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\concrete\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\concrete\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\concrete\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\concrete\bodyfall_2",1,1,50}}};
			dirt[] = {{"\dz\sounds\effects\animals\movement\bird_\dirt\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\dirt\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\dirt\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\dirt\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\dirt\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\dirt\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\dirt\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\dirt\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\dirt\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\dirt\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\dirt\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\dirt\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\dirt\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\dirt\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\dirt\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\dirt\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\dirt\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\dirt\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\dirt\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\dirt\bodyfall_2",1,1,50}}};
			forest[] = {{"\dz\sounds\effects\animals\movement\bird_\forest\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\forest\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\forest\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\forest\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\forest\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\forest\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\forest\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\forest\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\forest\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\forest\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\forest\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\forest\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\forest\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\forest\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\forest\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\forest\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\forest\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\forest\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\forest\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\forest\bodyfall_2",1,1,50}}};
			grass[] = {{"\dz\sounds\effects\animals\movement\bird_\grass\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\grass\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\grass\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\grass\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\grass\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\grass\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\grass\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\grass\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\grass\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\grass\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\grass\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\grass\bodyfall_2",1,1,50}}};
			drygrass[] = {{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\grass_dry\bodyfall_2",1,1,50}}};
			gravel[] = {{"\dz\sounds\effects\animals\movement\bird_\gravel\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\gravel\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\gravel\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\gravel\bodyfall_2",1,1,50}}};
			gravel2[] = {{"\dz\sounds\effects\animals\movement\bird_\gravel\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\gravel\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\gravel\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\gravel\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\gravel\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\gravel\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\gravel\bodyfall_2",1,1,50}}};
			metal[] = {{"\dz\sounds\effects\animals\movement\bird_\metal\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\metal\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\metal\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\metal\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\metal\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\metal\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\metal\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\metal\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\metal\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\metal\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\metal\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\metal\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\metal\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\metal\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\metal\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\metal\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\metal\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\metal\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\metal\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\metal\bodyfall_2",1,1,50}}};
			mud[] = {{"\dz\sounds\effects\animals\movement\bird_\mud\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\mud\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\mud\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\mud\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\mud\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\mud\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\mud\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\mud\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\mud\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\mud\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\mud\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\mud\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\mud\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\mud\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\mud\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\mud\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\mud\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\mud\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\mud\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\mud\bodyfall_2",1,1,50}}};
			road[] = {{"\dz\sounds\effects\animals\movement\bird_\road\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\road\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\road\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\road\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\road\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\road\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\road\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\road\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\road\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\road\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\road\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\road\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\road\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\road\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\road\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\road\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\road\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\road\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\road\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\road\bodyfall_2",1,1,50}}};
			rock[] = {{"\dz\sounds\effects\animals\movement\bird_\rock\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\rock\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\rock\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\rock\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\rock\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\rock\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\rock\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\rock\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\rock\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\rock\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\rock\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\rock\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\rock\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\rock\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\rock\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\rock\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\rock\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\rock\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\rock\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\rock\bodyfall_2",1,1,50}}};
			sand[] = {{"\dz\sounds\effects\animals\movement\bird_\sand\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\sand\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\sand\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\sand\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\sand\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\sand\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\sand\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\sand\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\sand\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\sand\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\sand\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\sand\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\sand\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\sand\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\sand\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\sand\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\sand\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\sand\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\sand\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\sand\bodyfall_2",1,1,50}}};
			water[] = {{"\dz\sounds\effects\animals\movement\bird_\water\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\water\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\water\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\water\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\water\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\water\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\water\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\water\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\water\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\water\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\water\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\water\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\water\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\water\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\water\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\water\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\water\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\water\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\water\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\water\bodyfall_2",1,1,50}}};
			wood[] = {{"\dz\sounds\effects\animals\movement\bird_\wood\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_2",1,1,50}}};
			wood_int[] = {{"\dz\sounds\effects\animals\movement\bird_\wood\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_2",1,1,50}}};
			parkety[] = {{"\dz\sounds\effects\animals\movement\bird_\wood\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\wood\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\wood\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\wood\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\wood\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\wood\bodyfall_2",1,1,50}}};
			steel[] = {{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_2",1,1,50}}};
			hallway[] = {{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_2",1,1,50}}};
			carpet[] = {{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_2",1,1,50}}};
			wave_plate[] = {{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_2",1,1,50}}};
			lepenka[] = {{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_2",1,1,50}}};
			tasky[] = {{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50},{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_1",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_3",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_5",1,1,50}},{"b_stepl",{"\dz\sounds\effects\animals\movement\bird_\default\step_7",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_2",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_4",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_6",1,1,50}},{"b_stepr",{"\dz\sounds\effects\animals\movement\bird_\default\step_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_1",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_2",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_3",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_4",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_5",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_6",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_7",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_8",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_9",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_10",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_11",1,1,50}},{"b_grazing",{"\dz\sounds\effects\animals\movement\bird_\default\grazing_12",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_0",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_1",1,1,50}},{"b_bodyfall",{"\dz\sounds\effects\animals\movement\bird_\default\bodyfall_2",1,1,50}}};
		};
		newAnimSystemSoundStepOverride = "walk";
		scope = 0;
		model = "\DZ\animals\gallus_gallus_domesticus_feminam\gallus_gallus_domesticus_feminam.p3d";
		armor = 1.1;
		moves = "CfgMovesGallusGallusFeminam";
		hiddenSelections[] = {"Camo"};
		class Skinning
		{
			class ObtainedSteaks
			{
				item = "Meat_ChickenBreast";
				count = 2;
				quantityMinMax[] = {0.25,1.0};
			};
			class ObtainedGuts
			{
				item = "Food_SmallGuts";
				count = 1;
				quantity = 1;
			};
			class ObtainedFeathers
			{
				item = "Crafting_ChickenFeather";
				count = 1;
				quantity = 20;
			};
			class ObtainedBones
			{
				item = "Consumable_Bones";
				count = 1;
				quantity = 2;
				transferToolDamage = 1;
			};
		};
		class AIAgentTemplate
		{
			name = "hen";
			HeadLookBoneName = "pin_lookat";
			teamName = "AmbientLife";
			class PathAgent
			{
				radius = 0.3;
				height = 0.4;
			};
			class BehaviourHLAmbientLife
			{
				agentPathLength = 20.0;
				agentPathUpdateDelta = 2.0;
				agentPathMinLength = 2.5;
				class SlotCalm
				{
					class BehaviourAmbientLifeCalm
					{
						walkWeight = 25;
						idle1Weight = 25;
						idle2Weight = 0;
						idle3Weight = 25;
						walkingDurationMin = 5.0;
						walkingDurationMax = 10.0;
						idle1DurationMin = 5.0;
						idle1DurationMax = 10.0;
						idle2DurationMin = 5.0;
						idle2DurationMax = 10.0;
						idle3DurationMin = 5.0;
						idle3DurationMax = 10.0;
						class WalkingMovement
						{
							maxSpeed = 0.1;
							minSpeed = 0.0;
							acceleration = 5.0;
							maxAngleSpeed = 90.0;
							slowRadius = 0.0;
							stopRadius = 0.5;
						};
					};
				};
				class SlotNonSpecificThreat
				{
					class BehaviourNonSpecificThreat
					{
						lookWeight = 30;
						sniffWeight = 0;
						sniffDuration = 0.5;
						lookDuration = 6.0;
					};
				};
				class SlotAlerted
				{
					class BehaviourGoToTarget
					{
						class Movement
						{
							maxSpeed = 3.0;
							minSpeed = 1.0;
							acceleration = 5.0;
							maxAngleSpeed = 180.0;
							slowRadius = 1.0;
							stopRadius = 2.0;
							slowToTurn = 1;
							smoothAcceleration = 1;
							pathFilter = "ChickenOnRun";
							startAnimationMaxSpeed = 0.9;
						};
					};
				};
				class AlertSystem
				{
					visionToAlertMultiplier = 10;
					noiseToAlertMultiplier = 1.0;
					damageToAlertMultiplier = 1e+006;
					class Calm
					{
						dropSpeed = 2;
						dropDelay = 3;
						maxAlertValue = 30;
					};
					class NonSpecificThreat
					{
						dropSpeed = 6;
						dropDelay = 3;
						maxAlertValue = 50;
					};
					class Alerted
					{
						dropSpeed = 10;
						dropDelay = 0;
						maxAlertValue = 100;
					};
				};
			};
			class NoiseSystemParams
			{
				rangeMin = 2.0;
				rangeMax = 15.0;
				rangeShotMin = 100.0;
				rangeShotMax = 300.0;
				class NoiseStrengthTeamMultipliers
				{
					BigGame = 0.8;
					Zombies = 1.0;
					Player = 1.0;
				};
			};
			class TargetSystemAmbientLife
			{
				visionManSizeStand = 1.0;
				visionManSizeCrouch = 0.8;
				visionManSizeProne = 0.45;
				visionRangeMin = 2.0;
				visionRangeMax = 15.0;
				visionNightMinMult = 1.0;
				visionNightMaxMult = 0.5;
			};
		};
		class AnimSystem
		{
			meshObject = "dz\animals\gallus_gallus_domesticus_feminam\data\gallus_gallus_domesticus_feminam_skeleton.xob";
			animGraph = "dz\animals\animations\hen_skeleton\AG_hen_skeleton.ag";
			class AnimEventSounds
			{
				class hen_cluck_a
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_a\cluck_a_0","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_1","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_2","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_3","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_4","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_5","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_6","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_7","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_8","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_9","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_10","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_11","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_12","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_13","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_14","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_15","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_16","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_17","DZ\sounds\effects\animals\hen\cluck_a\cluck_a_18"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_a_high
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_a_high\cluck_a_high_0"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_b
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_b\cluck_b_0","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_1","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_2","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_3","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_4","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_5","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_6","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_7","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_8","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_9","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_10","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_11","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_12","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_13","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_14","DZ\sounds\effects\animals\hen\cluck_b\cluck_b_15"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_b_high
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_b_high\cluck_b_high_0","DZ\sounds\effects\animals\hen\cluck_b_high\cluck_b_high_1","DZ\sounds\effects\animals\hen\cluck_b_high\cluck_b_high_2","DZ\sounds\effects\animals\hen\cluck_b_high\cluck_b_high_3","DZ\sounds\effects\animals\hen\cluck_b_high\cluck_b_high_4","DZ\sounds\effects\animals\hen\cluck_b_high\cluck_b_high_5","DZ\sounds\effects\animals\hen\cluck_b_high\cluck_b_high_6"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_c
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_c\cluck_c_0","DZ\sounds\effects\animals\hen\cluck_c\cluck_c_1","DZ\sounds\effects\animals\hen\cluck_c\cluck_c_2","DZ\sounds\effects\animals\hen\cluck_c\cluck_c_3","DZ\sounds\effects\animals\hen\cluck_c\cluck_c_4","DZ\sounds\effects\animals\hen\cluck_c\cluck_c_5","DZ\sounds\effects\animals\hen\cluck_c\cluck_c_6","DZ\sounds\effects\animals\hen\cluck_c\cluck_c_7"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_c_high
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_c_high\cluck_c_high_0"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_d
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_d\cluck_d_0","DZ\sounds\effects\animals\hen\cluck_d\cluck_d_1","DZ\sounds\effects\animals\hen\cluck_d\cluck_d_2","DZ\sounds\effects\animals\hen\cluck_d\cluck_d_3","DZ\sounds\effects\animals\hen\cluck_d\cluck_d_4"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_d_high
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_d_high\cluck_d_high_0"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_e
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_e\cluck_e_0","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_1","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_2","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_3","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_4","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_5","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_6","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_7","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_8","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_9","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_10","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_11","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_12","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_13","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_14","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_15","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_16","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_17","DZ\sounds\effects\animals\hen\cluck_e\cluck_e_18"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_e_high
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_e_high\cluck_e_high_0","DZ\sounds\effects\animals\hen\cluck_e_high\cluck_e_high_1","DZ\sounds\effects\animals\hen\cluck_e_high\cluck_e_high_2"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_silky
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_silky\cluck_silky_0"};
					volume = 1;
					distance = 70;
				};
				class hen_cluck_silky_high
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\cluck_silky_high\cluck_silky_high_0","DZ\sounds\effects\animals\hen\cluck_silky_high\cluck_silky_high_1","DZ\sounds\effects\animals\hen\cluck_silky_high\cluck_silky_high_2","DZ\sounds\effects\animals\hen\cluck_silky_high\cluck_silky_high_3","DZ\sounds\effects\animals\hen\cluck_silky_high\cluck_silky_high_4","DZ\sounds\effects\animals\hen\cluck_silky_high\cluck_silky_high_5","DZ\sounds\effects\animals\hen\cluck_silky_high\cluck_silky_high_6"};
					volume = 1;
					distance = 70;
				};
				class hen_scream
				{
					sounds[] = {"DZ\sounds\effects\animals\hen\scream\scream_0"};
					volume = 1;
					distance = 70;
				};
				class flapping
				{
					sounds[] = {"DZ\sounds\effects\animals\common\bird\default\flapping_0","DZ\sounds\effects\animals\common\bird\default\flapping_1","DZ\sounds\effects\animals\common\bird\default\flapping_2"};
					volume = 1;
					distance = 50;
				};
			};
		};
	};
	class Animal_GallusGallusDomesticusF_Brown: Animal_GallusGallusDomesticusF
	{
		scope = 2;
		displayName = "Gallus Gallus Domesticus Feminam Brow";
		hiddenSelectionsTextures[] = {"dz\animals\gallus_gallus_domesticus_feminam\data\hen_brown_co.paa"};
	};
	class Animal_GallusGallusDomesticusF_Spotted: Animal_GallusGallusDomesticusF
	{
		scope = 2;
		displayName = "Gallus Gallus Domesticus Feminam Spotted";
		hiddenSelectionsTextures[] = {"dz\animals\gallus_gallus_domesticus_feminam\data\hen_spotted_co.paa"};
	};
	class Animal_GallusGallusDomesticusF_White: Animal_GallusGallusDomesticusF
	{
		scope = 2;
		displayName = "Gallus Gallus Domesticus White";
		hiddenSelectionsTextures[] = {"dz\animals\gallus_gallus_domesticus_feminam\data\hen_white_co.paa"};
	};
};
